### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by Wemago** [yidemir/mikro#1]
Just saw that you updated Mikro. 

Will you bring the route\url feature for this one?
Also will you be adding route naming and optional parameter to the routing?

Pagination example
`/blog/{page:num}?`

I would create a new function compile and move the regex part to it, returning the path. This would make map function a bit cleaner.

Nice job with the update.
Would be interesting to see an update to the App one ;)

**Comment by yidemir** [comment]
Hello @Wemago,
I will be publishing the Optional parameter feature soon, thank you for your suggestion and comment. An update for the Demir\App will also be coming soon. :)

Stay in follow!
